"use client";

import { useEffect, useState } from "react";
import { Bar, BarChart, Cell, LabelList, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

/**
 * /analytics — telemetry report layer. Reads the BUNDLED static `/analytics.json`
 * (regenerated by scripts/build_analytics.py, published via publish_analytics.sh →
 * `vercel --prod`). No API call — a git-free snapshot that refreshes on publish.
 * Charts: Recharts. The family×model heatmap stays a custom grid (heatmaps aren't
 * a Recharts primitive).
 */

type SrcYield = { techniques: number; graduated: number; grad_rate: number };
type Analytics = {
  generated_at?: string;
  capability: {
    strategies_total: number; graduated: number; graduation_rate: number | null;
    graduations_by_modality: Record<string, number>;
    overall_breach_rate: number | null; validity_rate: number | null;
  };
  discovery: {
    source_yield: Record<string, SrcYield>;
    modality_growth_by_source_month: Record<string, { techniques: number; graduated: number }>;
  };
  contextual: {
    global_best_family: string | null; crossover_models: number; routing_verdict: string;
    family_x_model_breach: Record<string, Record<string, number>>;
  };
  allocation: { reachability?: number; starvation_rate?: number; avg_rank_of_winner?: number; avg_ladder_depth?: number };
  research: {
    opportunity_cost_starved_shots?: number; opportunity_cost_pct_of_eligible?: number;
    early_stop_bias?: number; exploration_efficiency?: number; scheduler_allocation_quality?: number;
  };
  cost: { total_breach_spend_usd: number; cost_per_breach_usd: number | null; cost_per_graduation_usd: number | null };
};

const GREEN = "#00ff88", ORANGE = "#ff6b00", RED = "#ff003c";
const pct = (x: number | null | undefined) => (x == null ? "—" : `${Math.round(x * 100)}%`);
const num = (x: number | null | undefined, d = 2) => (x == null ? "—" : x.toFixed(d));
const short = (m: string) => (m.split("/").pop() ?? m).replace(/-?\d[\d.-]*$/, "").replace(/-instruct$/, "").slice(0, 12);
const hex = (r: number) => (r >= 0.5 ? RED : r >= 0.25 ? ORANGE : r > 0 ? GREEN : "#3a3a44");
const gradHex = (r: number) => (r >= 0.25 ? GREEN : r >= 0.12 ? ORANGE : "rgba(0,255,136,0.4)");
function heatStyle(r: number | undefined): React.CSSProperties {
  if (r == null) return { background: "rgba(120,120,140,0.08)" };
  const rgb = r >= 0.5 ? "255,0,60" : r >= 0.25 ? "255,107,0" : "0,255,136";
  return { background: `rgba(${rgb},${(0.12 + r * 0.6).toFixed(2)})` };
}
const txt = (r: number) => (r >= 0.5 ? "text-rogue-red" : r >= 0.25 ? "text-rogue-orange" : r > 0 ? "text-rogue-green" : "text-muted-foreground");

type Pt = { full?: string; label?: string; techniques?: number; graduated?: number; gradRate?: number; avg?: number };
function ChartTip({ active, payload }: { active?: boolean; payload?: { payload: Pt }[] }) {
  if (!active || !payload?.length) return null;
  const d = payload[0].payload;
  return (
    <div className="rounded border border-rogue-green/40 bg-[#0a0a0f]/95 px-2.5 py-1.5 text-xs font-mono shadow-xl">
      <p className="text-rogue-green mb-0.5">{d.full ?? d.label}</p>
      {d.techniques != null && <p className="text-muted-foreground">techniques <span className="text-foreground tabular-nums">{d.techniques}</span></p>}
      {d.graduated != null && <p className="text-muted-foreground">graduated <span className="text-foreground tabular-nums">{d.graduated}</span></p>}
      {d.gradRate != null && <p className="text-muted-foreground">grad-rate <span className="tabular-nums" style={{ color: gradHex(d.gradRate) }}>{pct(d.gradRate)}</span></p>}
      {d.avg != null && <p className="text-muted-foreground">avg breach <span className="tabular-nums" style={{ color: hex(d.avg) }}>{pct(d.avg)}</span></p>}
    </div>
  );
}

function Stat({ label, value, sub, tone = "green" }: { label: string; value: string; sub?: string; tone?: "green" | "orange" | "blue" }) {
  const color = tone === "orange" ? "var(--rogue-orange)" : tone === "blue" ? "#6ab0ff" : "var(--rogue-green)";
  return (
    <div className="rounded-lg border border-border p-4 bg-card/40 hover:bg-card/70 transition-colors" style={{ borderLeftWidth: 3, borderLeftColor: color }}>
      <p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">{label}</p>
      <p className="text-2xl font-bold tabular-nums mt-1" style={{ color }}>{value}</p>
      {sub && <p className="text-[11px] text-muted-foreground mt-0.5">{sub}</p>}
    </div>
  );
}

export default function AnalyticsPage() {
  const [a, setA] = useState<Analytics | null>(null);
  const [err, setErr] = useState(false);
  const [thresh, setThresh] = useState(0);
  const [focusFam, setFocusFam] = useState<string | null>(null);
  useEffect(() => {
    fetch("/analytics.json", { cache: "no-store" }).then((r) => (r.ok ? r.json() : Promise.reject())).then(setA).catch(() => setErr(true));
  }, []);

  if (err) return <Shell><p className="text-muted-foreground">analytics.json not found — run <code>scripts/publish_analytics.sh</code>.</p></Shell>;
  if (!a) return <Shell><p className="text-rogue-green animate-pulse font-mono text-sm">loading telemetry…</p></Shell>;

  const srcData = Object.entries(a.discovery.source_yield).map(([src, v]) => ({ full: src, label: src, techniques: v.techniques, graduated: v.graduated, gradRate: v.grad_rate }));
  const growthData = Object.entries(a.discovery.modality_growth_by_source_month).map(([m, v]) => ({ full: m, label: m.slice(2), techniques: v.techniques, graduated: v.graduated, recent: m >= "2026-05" }));
  const matrix = a.contextual.family_x_model_breach || {};
  const families = Object.entries(matrix).map(([f, m]) => ({ f, m })).sort((x, y) => (Math.max(...Object.values(y.m)) - Math.min(...Object.values(y.m))) - (Math.max(...Object.values(x.m)) - Math.min(...Object.values(x.m))));
  const models = Array.from(new Set(families.flatMap((r) => Object.keys(r.m))));
  const modelVuln = models.map((mo) => { const rs = families.map((f) => f.m[mo]).filter((r): r is number => r != null); const avg = rs.length ? rs.reduce((p, c) => p + c, 0) / rs.length : 0; return { full: short(mo), label: short(mo), avg, avgPct: `${Math.round(avg * 100)}%` }; }).sort((x, y) => y.avg - x.avg);

  return (
    <Shell generatedAt={a.generated_at}>
      <Section title="Capability" tag="what graduates, how cheaply">
        <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
          <Stat label="Strategies" value={String(a.capability.strategies_total)} tone="blue" />
          <Stat label="Graduated" value={`${a.capability.graduated}`} sub={`${pct(a.capability.graduation_rate)} rate`} tone="green" />
          <Stat label="Cost / graduation" value={a.cost.cost_per_graduation_usd != null ? `$${num(a.cost.cost_per_graduation_usd)}` : "—"} tone="green" />
          <Stat label="Validity rate" value={pct(a.capability.validity_rate)} sub="real tests ÷ attempts" tone="blue" />
          <Stat label="Overall breach" value={pct(a.capability.overall_breach_rate)} tone="orange" />
          <Stat label="Total spend" value={`$${num(a.cost.total_breach_spend_usd)}`} sub={`$${num(a.cost.cost_per_breach_usd, 4)} / breach`} tone="green" />
        </div>
        <div className="flex gap-2 mt-3 flex-wrap">
          {Object.entries(a.capability.graduations_by_modality).map(([k, v]) => (
            <span key={k} className="font-mono text-[11px] px-2 py-1 rounded border border-rogue-green/40 bg-rogue-green/10 text-rogue-green">{k} · {v} graduated</span>
          ))}
        </div>
      </Section>

      <Section title="Discovery · source yield" tag="bar = volume · color = graduation rate · hover for detail">
        <ResponsiveContainer width="100%" height={Math.max(160, srcData.length * 34)}>
          <BarChart layout="vertical" data={srcData} margin={{ top: 4, right: 36, bottom: 4, left: 4 }}>
            <XAxis type="number" hide />
            <YAxis type="category" dataKey="label" width={130} tick={{ fontSize: 11, fill: "#8a8a99", fontFamily: "var(--font-geist-mono)" }} tickLine={false} axisLine={false} />
            <Tooltip content={<ChartTip />} cursor={{ fill: "rgba(0,255,136,0.06)" }} />
            <Bar dataKey="techniques" radius={[0, 4, 4, 0]} animationDuration={650} label={{ position: "right", fontSize: 10, fill: "#8a8a99" }}>
              {srcData.map((d, i) => <Cell key={i} fill={gradHex(d.gradRate)} />)}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </Section>

      <Section title="Growth · techniques by source month" tag="when the harvested attacks were published — recent months brighter">
        <ResponsiveContainer width="100%" height={210}>
          <BarChart data={growthData} margin={{ top: 12, right: 8, bottom: 0, left: -18 }}>
            <XAxis dataKey="label" tick={{ fontSize: 9, fill: "#8a8a99" }} tickLine={false} axisLine={{ stroke: "var(--border)" }} interval={0} />
            <YAxis tick={{ fontSize: 10, fill: "#8a8a99" }} tickLine={false} axisLine={false} width={26} allowDecimals={false} />
            <Tooltip content={<ChartTip />} cursor={{ fill: "rgba(0,255,136,0.06)" }} />
            <Bar dataKey="techniques" radius={[3, 3, 0, 0]} animationDuration={700} label={{ position: "top", fontSize: 9, fill: "#8a8a99" }}>
              {growthData.map((d, i) => <Cell key={i} fill={d.recent ? GREEN : "rgba(0,255,136,0.4)"} />)}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </Section>

      <Section title="Contextual breach heatmap" tag="family × target model · click a row to focus · click the model bars to rank vulnerability">
        <p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground mb-1">model vulnerability — avg breach rate across families</p>
        <ResponsiveContainer width="100%" height={Math.max(120, modelVuln.length * 26)}>
          <BarChart layout="vertical" data={modelVuln} margin={{ top: 2, right: 40, bottom: 2, left: 4 }}>
            <XAxis type="number" domain={[0, 1]} hide />
            <YAxis type="category" dataKey="label" width={100} tick={{ fontSize: 10, fill: "#8a8a99", fontFamily: "var(--font-geist-mono)" }} tickLine={false} axisLine={false} />
            <Tooltip content={<ChartTip />} cursor={{ fill: "rgba(255,255,255,0.04)" }} />
            <Bar dataKey="avg" radius={[0, 4, 4, 0]} animationDuration={650}>
              {modelVuln.map((d, i) => <Cell key={i} fill={hex(d.avg)} />)}
              <LabelList dataKey="avgPct" position="right" fontSize={10} fill="#aaa" />
            </Bar>
          </BarChart>
        </ResponsiveContainer>

        <div className="flex items-center gap-3 mt-4 mb-2 flex-wrap text-xs">
          <span className="text-muted-foreground font-mono uppercase tracking-wider">heatmap filter</span>
          {([["all", 0], ["≥30%", 0.3], ["≥60%", 0.6]] as [string, number][]).map(([lbl, th]) => (
            <button key={lbl} onClick={() => setThresh(th)} className={`px-2.5 py-1 rounded border font-mono transition-colors ${thresh === th ? "border-rogue-green bg-rogue-green/15 text-rogue-green" : "border-border text-muted-foreground hover:bg-card/60"}`}>{lbl}</button>
          ))}
          <span className="ml-auto flex items-center gap-1.5 text-[10px] text-muted-foreground">
            <span className="w-3 h-3 rounded-sm" style={heatStyle(0.1)} />low<span className="w-3 h-3 rounded-sm" style={heatStyle(0.4)} />mid<span className="w-3 h-3 rounded-sm" style={heatStyle(0.8)} />high
          </span>
        </div>
        <div className="overflow-x-auto">
          <div className="inline-grid gap-0.5" style={{ gridTemplateColumns: `7.5rem repeat(${models.length}, minmax(3.2rem,1fr))` }}>
            <div />
            {models.map((mo) => <div key={mo} className="text-[9px] font-mono text-muted-foreground text-center pb-1 truncate" title={mo}>{short(mo)}</div>)}
            {families.map(({ f, m }) => <FamilyRow key={f} f={f} m={m} models={models} thresh={thresh} focused={focusFam === f} dim={!!focusFam && focusFam !== f} onClick={() => setFocusFam(focusFam === f ? null : f)} />)}
          </div>
        </div>
        <p className="text-xs text-muted-foreground mt-3">Best family <span className="font-mono text-rogue-green">{a.contextual.global_best_family}</span> · crossover models <span className="tabular-nums">{a.contextual.crossover_models}</span> → {a.contextual.routing_verdict}</p>
      </Section>

      <Section title="Allocation & research" tag="the §10.10 scheduler dataset (aggregates over all runs)">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          <Stat label="Reachability" value={pct(a.allocation.reachability)} sub="executed ÷ eligible" tone="green" />
          <Stat label="Scheduler quality" value={pct(a.research.scheduler_allocation_quality)} sub="winners land early" tone="green" />
          <Stat label="Exploration eff." value={pct(a.research.exploration_efficiency)} sub="strategy coverage" tone="green" />
          <Stat label="Starvation" value={pct(a.allocation.starvation_rate)} sub="early-stop (by design)" tone="orange" />
          <Stat label="Early-stop bias" value={pct(a.research.early_stop_bias)} tone="orange" />
          <Stat label="Opportunity cost" value={`${a.research.opportunity_cost_starved_shots ?? "—"}`} sub={`${pct(a.research.opportunity_cost_pct_of_eligible)} of eligible`} tone="orange" />
          <Stat label="Avg rank winner" value={num(a.allocation.avg_rank_of_winner, 1)} tone="blue" />
          <Stat label="Avg ladder depth" value={num(a.allocation.avg_ladder_depth, 1)} tone="blue" />
        </div>
      </Section>
    </Shell>
  );
}

function FamilyRow({ f, m, models, thresh, focused, dim, onClick }: { f: string; m: Record<string, number>; models: string[]; thresh: number; focused: boolean; dim: boolean; onClick: () => void; }) {
  return (
    <>
      <button onClick={onClick} className={`text-[10px] font-mono text-left pr-2 truncate transition-opacity hover:text-rogue-green ${focused ? "text-rogue-green" : "text-muted-foreground"} ${dim ? "opacity-40" : ""}`} title={f} style={{ alignSelf: "center" }}>{f}</button>
      {models.map((mo) => {
        const r = m[mo];
        const muted = thresh > 0 && (r ?? 0) < thresh;
        return (
          <div key={mo} title={`${f} × ${short(mo)}: ${r == null ? "n/a" : pct(r)}`} style={heatStyle(r)}
            className={`aspect-[2/1] rounded-sm flex items-center justify-center text-[9px] tabular-nums font-bold transition-all cursor-default ${dim || muted ? "opacity-25" : ""} ${r != null ? txt(r) : "text-muted-foreground/50"} hover:ring-1 hover:ring-foreground/40 hover:!opacity-100`}>{r == null ? "" : Math.round(r * 100)}</div>
        );
      })}
    </>
  );
}

function Shell({ children, generatedAt }: { children: React.ReactNode; generatedAt?: string }) {
  return (
    <main className="flex-1 bg-rogue-grid bg-rogue-spotlight">
      <div className="max-w-5xl mx-auto px-6 py-10 space-y-8">
        <header className="space-y-2 animate-rogue-fade-up">
          <p className="font-mono text-[10px] uppercase tracking-[0.2em] text-rogue-green flex items-center gap-2">
            <span className="inline-block w-1.5 h-1.5 rounded-full bg-rogue-green animate-rogue-pulse-green" />
            /analytics {generatedAt ? `· ${generatedAt.slice(0, 16).replace("T", " ")}Z` : ""}
          </p>
          <h1 className="text-4xl font-bold tracking-tight">Telemetry</h1>
          <p className="text-sm text-muted-foreground">Capability, discovery, allocation &amp; research metrics from the live breach matrix — a published snapshot.</p>
        </header>
        {children}
      </div>
    </main>
  );
}

function Section({ title, tag, children }: { title: string; tag?: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3 animate-rogue-fade-up">
      <div className="flex items-baseline gap-3 flex-wrap border-b border-border/40 pb-2">
        <h2 className="text-lg font-bold tracking-tight">{title}</h2>
        {tag && <p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{tag}</p>}
      </div>
      {children}
    </section>
  );
}
